version: '3'

services:
  app:
    build: .
    image: fernandofogliato/backend-nestjs
    entrypoint: ./.docker/entrypoint.sh
    container_name: backend-nestjs
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on: [db]

  db:
    build: ./.docker/mysql
    container_name: backend-nestjs-db
    restart: always
    tty: true
    ports:
      - 33006:3306
    expose:
      - 3306
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=backend-nestjs
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
